In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from tensorflow.keras.models import Sequential,load_model
import pickle

In [2]:
model=load_model("ann_model.h5")
with open("standardscaler.pkl","rb") as f:
				scaler=pickle.load(f)
with open("labelencoder.pkl","rb") as f:
				encoder=pickle.load(f)	
with open("onehotencoder.pkl","rb") as f:
				onehot=pickle.load(f)

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [3]:
input_data = {
    'CreditScore': 600,
    'Geography': 'France',
    'Gender': 'Male',
    'Age': 40,
    'Tenure': 3,
    'Balance': 60000,
    'NumOfProducts': 2,
    'HasCrCard': 1,
    'IsActiveMember': 1,
    'EstimatedSalary': 50000
}

In [4]:
df=pd.DataFrame([input_data])
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,Male,40,3,60000,2,1,1,50000

In [5]:
# df["Geography"]=encoder.transform(df["Geography"])
df["Gender"]=encoder.transform(df["Gender"])
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,1,40,3,60000,2,1,1,50000

In [6]:
geo = onehot.transform([["France"]]).toarray()

c:\Users\saian\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

In [7]:
df=pd.concat([df,pd.DataFrame(geo,columns=onehot.get_feature_names_out())],axis=1)
df.drop("Geography",axis=1,inplace=True)
df.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,1,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [11]:
print(model.predict(scaler.transform(df)))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
[[0.02438814]]

In [16]:
print(onehot.categories_[0])

['France' 'Germany' 'Spain']

In [17]:
print(encoder.classes_)

['Female' 'Male']

In [19]:
print(encoder.transform(["Male"])[0])

1

In [23]:
geo_encoded = onehot.transform([["France"]]).toarray()
geo_encoded

c:\Users\saian\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[1., 0., 0.]])

In [28]:
x=[1,2,3]
y=[4,5,6]
z=np.concatenate([[x], [y]],	axis=1)
z

array([[1, 2, 3, 4, 5, 6]])